name: cricket
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  firebase_auth: ^5.4.2  # Use a stable version
  firebase_auth_web: ^5.13.8  # Downgrade to a previous stable version
  provider: ^6.1.2
  pdf: ^3.10.8
  path_provider: ^2.1.3
  fl_chart: ^0.70.2
  cupertino_icons: ^1.0.8
  firebase_database: ^11.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Updated to latest stable version

flutter:
  uses-material-design: true
